### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/BitBasis.jl#3]
- [x] `takebit` <-> `getbit`

This following came directly from documentation:

- [x] `testany` -> `anymasked`, Return `true` if any masked position of index is 1.
- [x] `testall` -> `allmasked`, Return `true` if all masked position of index is 1.
- [x]  `testval` -> `ismasked_equal`,  Return `true` if bits at positions masked by `mask` equal to `1` are equal to `onemask`.

- [x] `nactive` -> `log2dim1`, `nactive` make no sense in this package.

**Comment by GiggleLiu** [comment]
1. getbit is not better than takebit, easy to get confused with setbit.

2, 3, 4 I prefer the original ones, testxxx returning Boolean  is consistent, and is easier for remembering.

5. Agree with the renaming, but it should not be exported

**Comment by Roger-luo** [comment]
update:

- [ ] `takebit/getbit` -> `readbit`
- [ ] `anymasked` -> `anyone`
- [ ] `allmasked` -> `allone`
- [ ] `ismasked_equal` -> `ismatch`

**Comment by GiggleLiu** [comment]
- [ ] `nbit`/`num_bits`/`nbit`

**Comment by Roger-luo** [comment]
all done!
