### ISSUE TITLE
`trailing_zeros(::BitStr)` is missing

### ISSUE THREAD

**Issue by jlbosse** [QuantumBFS/BitBasis.jl#30]
Currently `trailing_zeros()` is not defined for BitStrings. It is needed to make `StatsBase.countmap` work on Arrays of BitStrings. This in turn is useful whenever one wants to compute e.g. expectation values from measurement samples and not from the wavefunction to get more realistic noise.

As far as I understand one simply needs to change lines 91:93 in `BitBasis.jl` from 
```julia 
for op in [:count_ones, :count_zeros, :leading_ones, :leading_zeros]
    @eval Base.$op(a::BitStr) = Base.$op(buffer(a))
end
```
to 
```julia 
for op in [:count_ones, :count_zeros, :leading_ones, :leading_zeros, :trailing_zeros, :trailing_ones]
    @eval Base.$op(a::BitStr) = Base.$op(buffer(a))
end
```
If you want, I can open a PR although for such a small edit it is probably easier if one of the maintainers does it.

**Comment by Roger-luo** [comment]
yes, please, this looks like a rather simple change, a PR would be nice!

**Comment by jlbosse** [comment]
^^Done.
I also added the corresponding tests and for completeness included `trailing_ones()`.
