### ISSUE TITLE
Does BitBasis support efficient slicing?

### ISSUE THREAD

**Issue by hz-xiaxz** [QuantumBFS/BitBasis.jl#53]
I hope to slice the `LongBitStr` like the intrinsic `String` type in Julia. For example, for Julia `Strings` it works like
```julia-repl
julia> a = "abab"
"abab"

julia> a[1:2]
"ab"
```
where `a[1:2]` return the same `String`-typed result.

However for BitBasis 0.9.3 it returns a certain `Vector` type
```julia-repl
julia> b = bit"0101"
0101 ₍₂₎

julia> b[1:2]
2-element Vector{Int64}:
 1
 0

julia> BitStr(b[1:2])
01 ₍₂₎
```
which needs an extra operation to convert it back to `BitStr` type, consuming computation time.
Is it possible to overload the slicing operation or provide a `SubString` function like discussed in [StackOverflow](https://stackoverflow.com/questions/68141033/how-do-i-get-a-substring-of-a-string-in-julia)?

**Comment by GiggleLiu** [comment]
Resolved in #54 .
